### ISSUE TITLE
Pop and Pull not working

### ISSUE THREAD

**Issue by shwaydogg** [jagi/meteor-astronomy#149]
I attempted to reproduce the `pull` and `pop` documentation, but both methods are returning `undefined`.  See the example code below.  [For convenience I've also included the snippets from the documentation after it].

Am I missing something or are they not working?

```
Phone = Astro.Class({
  name: 'Phone',
  fields: {
    number: 'number'
  }
});

Contacts = new Mongo.Collection('contacts');

Contact = Astro.Class({
  name: 'Contacts',
  collection: Contacts,
  /* ... */
  fields: {
    phones: {
      type: 'array',
      nested: 'Phone',
      default: function() {
        return [];
      }
    }
  }
});

var newContact = new Contact();
newContact.set('phones',
  [
    {number:8675309},
    {number:8675309},
    {number:8675309},
    {number: 123456789},
    {number: 123456789},
    {number: 123456789},
    {number:8675309},
    {number:2128675309},
  ]);

var newPulled = newContact.pull('phones', {number: 123456789});
var newPopped = newContact.pop('phones.number', 1);

console.log('NEW pulled:', newPulled);       // --> undefined
console.log('NEW popped:', newPopped);  // --> undefined
console.log('NEW contact:', newContact);  // --> unchanged

newContact.save();

var contact = Contacts.findOne({_id:newContact._id});

var pulled = contact.pull('phones', {number: 123456789});
var popped = contact.pop('phones.number', 1);

console.log('pulled:', pulled);      // --> undefined
console.log('popped:', popped); // --> undefined
console.log('contact:', contact); // --> unchanged
```

Pull example documentation:
```
Phone = Astro.Class({
  name: 'Phone',
  fields: {
    number: 'number'
  }
});

User = Astro.Class({
  name: 'User',
  /* ... */
  fields: {
    phones: {
      type: 'array',
      nested: 'Phone',
      default: function() {
        return [];
      }
    }
  }
});

var user = Users.findOne();
user.pull('phones', {
  number: 123456789
});
```

Pop Example Documentation:
```
Phone = Astro.Class({
  name: 'Phone',
  fields: {
    number: 'number'
  }
});

User = Astro.Class({
  name: 'User',
  /* ... */
  fields: {
    phones: {
      type: 'array',
      nested: 'Phone',
      default: function() {
        return [];
      }
    }
  }
});

var user = Users.findOne();
user.pop('phones', 1);
```

**Comment by shwaydogg** [comment]
Still occurs with a `.save()` between every method call:
```
Phone = Astro.Class({
  name: 'Phone',
  fields: {
    number: 'number'
  }
});

Contacts = new Mongo.Collection('contacts');

Contact = Astro.Class({
  name: 'Contacts',
  collection: Contacts,
  /* ... */
  fields: {
    phones: {
      type: 'array',
      nested: 'Phone',
      default: function() {
        return [];
      }
    }
  }
});

var newContact = new Contact();

newContact.save();

newContact.set('phones',
  [
    {number:8675309},
    {number:8675309},
    {number:8675309},
    {number: 123456789},
    {number: 123456789},
    {number: 123456789},
    {number:8675309},
    {number:2128675309},
  ]);

newContact.save();

var newPulled = newContact.pull('phones', {number: 123456789});
newContact.save();
var newPopped = newContact.pop('phones.number', 1);
newContact.save();

console.log('NEW pulled:', newPulled);
console.log('NEW popped:', newPopped);
console.log('NEW contact:', newContact);

newContact.save();

var contact = Contacts.findOne({_id:newContact._id});

contact.save();
var pulled = contact.pull('phones', {number: 123456789});
contact.save();
var popped = contact.pop('phones.number', 1);
contact.save();

console.log('pulled:', pulled);
console.log('popped:', popped);
console.log('contact:', contact);
```

**Comment by jagi** [comment]
Ok, if it goes about these operations they are checking values by reference what is wrong so I have to fix it. If it goes about the pop operation you did it on the phone.number field which is wrong. You can't pop from the object. You can only pop from the array.

**Comment by jagi** [comment]
Ok it's fixed and will appear in the next version with bug fixes

**Comment by jagi** [comment]
Ok new version published. I'm closing this issue for now. If you have any further question then just ask and I will answer it here.

**Comment by jazzdragon** [comment]
Hi,
I'm facing the same issue. I just updated to 1.1.5
my code is very similar, but here it is:

```javascript
ItemInCart = Astronomy.Class({
  name: 'ItemInCart',
  fields: {
    itemId: 'string',
    price: 'number'
  }
})

Customers = new Mongo.Collection('customers');
Customer = Astronomy.Class({
  name: 'Customer',
  collection: Customers,
  fields: {
    name: 'string',
    itemsInCart: {
      type: 'array',
      nested: 'ItemInCart',
      default: function(){ return []; }
    }
  }
});

// ...later
customer = Customers.findOne({_id: customerId});
customer.pull('itemsInCart', {itemId: itemId}) // the itemId here is the correct one
console.log customer // --> unchanged
customer.save() // --> no effect
```

**Comment by jagi** [comment]
The `ItemInCart` class has to fields, and the object that you are removing should have also to fields. It has to be equal to object that you are trying to pull. You should check what the `customer.itemsInCart` array contains.

**Comment by jazzdragon** [comment]
I see.
May I suggest having the option to only match one of the fields in the object?
I think that would make it more straight forward and easy.
Thanks again!

**Comment by jagi** [comment]
It won't not be possible using the Astronomy API. It's also not possible using MongoDB. It's the problem that should be solved by looking for the value in an array and later pulling this value.

```js
var value = _.find(customer.itemsInCart, function(item) {
  return item.itemId === itemId;
});
customer.pull('itemsInCart', value);
```

**Comment by jazzdragon** [comment]
cool, thanks

**Comment by shwaydogg** [comment]
Hi @jagi, thanks for jumping on this and putting out fixes!

With the slightly updated testing / reproduction code below I was able to confirm that the collection object is updated but pop and pull don't seem to be returning the removed items.  The console logs are still undefined for their return values.

Looking back at the docs they do not specifically indicate that they return the items removed from the document, however I think it's implied from the the names 'pull' and 'pop'.

```
if (!Meteor.isClient) return;

Phone = Astro.Class({
  name: 'Phone',
  fields: {
    number: 'number'
  }
});

Contacts = new Mongo.Collection('contacts');

Contact = Astro.Class({
  name: 'Contacts',
  collection: Contacts,
  /* ... */
  fields: {
    phones: {
      type: 'array',
      nested: 'Phone',
      default: function() {
        return [];
      }
    }
  }
});

var newContact = new Contact();

newContact.save();

newContact.set('phones',
  [
    {number:8675309},
    {number:8675309},
    {number:8675309},
    {number: 123456789},
    {number: 123456789},
    {number: 123456789},
    {number:8675309},
    {number:2128675309},
  ]);

newContact.save();
console.log('NEW contact starts:', newContact);

var newPulled = newContact.pull('phones', {number: 123456789});
newContact.save();
console.log('NEW contact post pull:', newContact);
var newPopped = newContact.pop('phones', 1);
newContact.save();

console.log('NEW pulled:', newPulled);          // --> undefined
console.log('NEW popped:', newPopped);     // --> undefined
console.log('NEW contact:', newContact);     // Now working! document has items removed

newContact.save();

var contact = Contacts.findOne({_id:newContact._id});

contact.save();
var pulled = contact.pull('phones', {number: 123456789});
contact.save();
var popped = contact.pop('phones', 1);
contact.save();

console.log('pulled:', pulled);       // --> undefined
console.log('popped:', popped);  // --> undefined
console.log('contact:', contact);   // Now working! document has items removed
````

**Comment by jagi** [comment]
The `pull()` method does not return pulled value. Take a look at how lodash implement the `pull()` method. It does not return pulled value but the array after pull. Astronomy does not return anything from from the `pull()` method. You probably want to now if the pull operation succeeded?

**Comment by shwaydogg** [comment]
Lodash does set a precedent that goes against `pull` returning the removed value/s, however in cs or at least js land, it's pretty clear that when we use the method `pop` we traditionally expect to have the removed elements returned.  This is cooked into js itself and data structure teaching.  

The docs further link pop to the js method pop when you write, "They correspond to the pop() and unshift() JavaScript methods accordingly." (Perhaps this was only intended in respect to the parameters provided to `pop`, but it could be interpreted either way).  

Furthermore, having pull and pop right next to each other as the only two which remove elements further seems to pair them together, at least when I see them, but perhaps that is not a fair argument.

In addition if we're going to use the Lodash example, there are other methods at alternatives that do return the removed values such as `_.remove`: http://devdocs.io/lodash/index#remove 

Best case scenario I'd hope to see `pull` and `pop` return the values they are removing.  I don't know what extra work may or may not be involved, however I think the good news is that the change shouldn't produce and breaking changes since they always return undefined at the moment.

**Comment by jagi** [comment]
OK so how would you see it working? It should return the pulled value only if it was pulled and `undefined` otherwise? What about pulling many values? Should it return array of pulled values? Or should it always return array but sometimes empty, sometimes with one pulled value and sometimes with all pulled values?

**Comment by shwaydogg** [comment]
I'd say always return an array.

**Comment by jagi** [comment]
Ok I've implemented returning a value from pull and pop methods. It will be published today.

**Comment by shwaydogg** [comment]
Just tested and looks great @jagi !  Speedy work!

**Comment by lsunsi** [comment]
pull and pop still not working for me.
I simple .pop(field, 1) does nothing for me, and neither does pulling a value from a plain string array.

Am I doing something wrong?

**Comment by shwaydogg** [comment]
@lsunsi example code will probably help :)

**Comment by jagi** [comment]
@lsunsi yes it would help :)

**Comment by lsunsi** [comment]
@shwaydogg @jagi 

![screen shot 2015-12-09 at 6 22 01 am](https://cloud.githubusercontent.com/assets/6089867/11680121/317b1ca6-9e3d-11e5-99b8-14c908966cb6.png)

**Comment by jagi** [comment]
You can't do it that way. It's limitation of Astronomy 1.0 that will be overcome in 2.0.
The `push` and `pop` operations can't be executed on the same field in one modification sequence. After pushing several values you should have a document first and later pop values.

**Comment by lsunsi** [comment]
@jagi 
Oh, ok. I get it.

Looking forward to 2.0 then.
Really like your package man, thanks!

**Comment by jagi** [comment]
It will be soon available :). I will inform when the RC version is ready and invite all people to tests.
